### ISSUE TITLE
Publish on hex.pm?

### ISSUE THREAD

**Issue by keichan34** [rjsamson/hexate#16]
It'd be nice if we could add this in deps as a hex package instead of having to specify git as the source.

https://hex.pm/docs/publish

**Comment by rjsamson** [comment]
Sure! Been meaning to get around to that - I'll do it tonight.

**Comment by keichan34** [comment]
Thanks :heart:

**Comment by rjsamson** [comment]
Done!

https://hex.pm/packages/hexate

Thanks for the reminder! :+1:

**Comment by suranyami** [comment]
sweet!

**Comment by rjsamson** [comment]
Also generated and uploaded docs here - http://hexdocs.pm/hexate/0.5.1/
